part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const GET_START = _Paths.GET_START;
  static const LOGIN = _Paths.LOGIN;
  static const VERIFICATION_CODE = _Paths.VERIFICATION_CODE;
  static const YOUR_NAME = _Paths.YOUR_NAME;
  static const ARY_PASSPORT = _Paths.ARY_PASSPORT;
  static const HIGHLIGHTE_REAL = _Paths.HIGHLIGHTE_REAL;
  static const HOUSE_RULE = _Paths.HOUSE_RULE;
  static const HIGHLIGHT_SELECT_MEDIA = _Paths.HIGHLIGHT_SELECT_MEDIA;
  static const SHARE_SPACE_TAPE = _Paths.SHARE_SPACE_TAPE;
  static const HIGHLIGHT_SELECT_EDIT = _Paths.HIGHLIGHT_SELECT_EDIT;
  static const EDIT_SHARE_SPACE_TAPE = _Paths.EDIT_SHARE_SPACE_TAPE;
  static const NAV_BAR = _Paths.NAV_BAR;
  static const EXPLORE = _Paths.EXPLORE;
  static const TRIPS = _Paths.TRIPS;
  static const PROFILE = _Paths.PROFILE;
  static const WELCOME = _Paths.WELCOME;
  static const SWAP_STAYS = _Paths.SWAP_STAYS;
  static const SELECT_LOCATION = _Paths.SELECT_LOCATION;
  static const CREDIT_SYSTEM = _Paths.CREDIT_SYSTEM;
  static const FINDING_HOMES = _Paths.FINDING_HOMES;
  static const ALL_AMENITIES = _Paths.ALL_AMENITIES;
  static const HOME = _Paths.HOME;
  static const NEXT_PAGE = _Paths.NEXT_PAGE;
  static const PROFILE_SETTING = _Paths.PROFILE_SETTING;
  static const MY_TRAVEL_PLAN = _Paths.MY_TRAVEL_PLAN;
  static const MY_SPACE = _Paths.MY_SPACE;
  static const SAMPLE_VIDEO = _Paths.SAMPLE_VIDEO;
  static const TRIP_REQUEST = _Paths.TRIP_REQUEST;
  static const EDIT_MY_PROFILE = _Paths.EDIT_MY_PROFILE;
  static const EDIT_ABOUT_ME = _Paths.EDIT_ABOUT_ME;
  static const EDIT_POD = _Paths.EDIT_POD;
  static const EDIT_TRAVEL_QUESTION = _Paths.EDIT_TRAVEL_QUESTION;
  static const EDIT_TRAVEL_INTEREST = _Paths.EDIT_TRAVEL_INTEREST;
  static const EDIT_LANGUAGE = _Paths.EDIT_LANGUAGE;
  static const EDIT_DREAM_DESTINATIONS = _Paths.EDIT_DREAM_DESTINATIONS;
  static const EDIT_FAVORITE_DESTINATIONS = _Paths.EDIT_FAVORITE_DESTINATIONS;
  static const EDIT_MY_SPACE_BASIC = _Paths.EDIT_MY_SPACE_BASIC;
  static const EDIT_MY_SPACE_ESSENTIAL = _Paths.EDIT_MY_SPACE_ESSENTIAL;
  static const EDIT_MY_SPACE_LOCATION = _Paths.EDIT_MY_SPACE_LOCATION;
  static const EDIT_MY_SPACE_QUESTION = _Paths.EDIT_MY_SPACE_QUESTION;
  static const EDIT_MY_SPACE_RULES = _Paths.EDIT_MY_SPACE_RULES;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const GET_START = '/get-start';
  static const LOGIN = '/login';
  static const VERIFICATION_CODE = '/verification-code';
  static const YOUR_NAME = '/your-name';
  static const ARY_PASSPORT = '/ary-passport';
  static const HIGHLIGHTE_REAL = '/highlighte-real';
  static const HOUSE_RULE = '/house-rule';
  static const HIGHLIGHT_SELECT_MEDIA = '/highlight-select-media';
  static const SHARE_SPACE_TAPE = '/share-space-tape';
  static const HIGHLIGHT_SELECT_EDIT = '/highlight-select-edit';
  static const EDIT_SHARE_SPACE_TAPE = '/edit-share-space-tape';
  static const NAV_BAR = '/nav-bar';
  static const EXPLORE = '/explore';
  static const TRIPS = '/trips';
  static const PROFILE = '/profile';
  static const WELCOME = '/welcome';
  static const SWAP_STAYS = '/swap-stays';
  static const SELECT_LOCATION = '/select-location';
  static const CREDIT_SYSTEM = '/credit-system';
  static const FINDING_HOMES = '/finding-homes';
  static const ALL_AMENITIES = '/all-amenities';
  static const HOME = '/home';
  static const NEXT_PAGE = '/next-page';
  static const PROFILE_SETTING = '/profile-setting';
  static const MY_TRAVEL_PLAN = '/my-travel-plan';
  static const MY_SPACE = '/my-space';
  static const SAMPLE_VIDEO = '/sample-video';
  static const TRIP_REQUEST = '/trip-request';
  static const EDIT_MY_PROFILE = '/edit-my-profile';
  static const EDIT_ABOUT_ME = '/edit-about-me';
  static const EDIT_POD = '/edit-pod';
  static const EDIT_TRAVEL_QUESTION = '/edit-travel-question';
  static const EDIT_TRAVEL_INTEREST = '/edit-travel-interest';
  static const EDIT_LANGUAGE = '/edit-language';
  static const EDIT_DREAM_DESTINATIONS = '/edit-dream-destinations';
  static const EDIT_FAVORITE_DESTINATIONS = '/edit-favorite-destinations';
  static const EDIT_MY_SPACE_BASIC = '/edit-my-space-basic';
  static const EDIT_MY_SPACE_ESSENTIAL = '/edit-my-space-essential';
  static const EDIT_MY_SPACE_LOCATION = '/edit-my-space-location';
  static const EDIT_MY_SPACE_QUESTION = '/edit-my-space-question';
  static const EDIT_MY_SPACE_RULES = '/edit-my-space-rules';
}
